/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellIndexRouteImport } from './routes/_authenticated/_shell/index'
import { Route as AuthenticatedShellInboxRouteImport } from './routes/_authenticated/_shell/inbox'
import { Route as AuthenticatedShellMyTasksRouteImport } from './routes/_authenticated/_shell/my-tasks'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell/settings'
import { Route as AuthenticatedShellProjectsNameRouteImport } from './routes/_authenticated/_shell/projects.$name'
import { Route as AuthenticatedShellProjectsNameIndexRouteImport } from './routes/_authenticated/_shell/projects.$name.index'
import { Route as AuthenticatedShellProjectsNameSettingsRouteImport } from './routes/_authenticated/_shell/projects.$name.settings'
import { Route as AuthenticatedShellProjectsNameLinksIndexRouteImport } from './routes/_authenticated/_shell/projects.$name.links.index'
import { Route as AuthenticatedShellProjectsNameLinksLinkRouteImport } from './routes/_authenticated/_shell/projects.$name.links.$link'
import { Route as AuthenticatedShellProjectsNameMilestonesIndexRouteImport } from './routes/_authenticated/_shell/projects.$name.milestones.index'
import { Route as AuthenticatedShellProjectsNameMilestonesMilestoneRouteImport } from './routes/_authenticated/_shell/projects.$name.milestones.$milestone'
import { Route as AuthenticatedShellProjectsNameModulesIndexRouteImport } from './routes/_authenticated/_shell/projects.$name.modules.index'
import { Route as AuthenticatedShellProjectsNameModulesModuleRouteImport } from './routes/_authenticated/_shell/projects.$name.modules.$module'
import { Route as AuthenticatedShellProjectsNameTasksTaskRouteImport } from './routes/_authenticated/_shell/projects.$name.tasks.$task'
import { Route as AuthenticatedShellProjectsNameViewsViewRouteImport } from './routes/_authenticated/_shell/projects.$name.views.$view'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellIndexRoute = AuthenticatedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellInboxRoute = AuthenticatedShellInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellMyTasksRoute =
  AuthenticatedShellMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProjectsNameRoute =
  AuthenticatedShellProjectsNameRouteImport.update({
    id: '/projects/$name',
    path: '/projects/$name',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProjectsNameIndexRoute =
  AuthenticatedShellProjectsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameSettingsRoute =
  AuthenticatedShellProjectsNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameLinksIndexRoute =
  AuthenticatedShellProjectsNameLinksIndexRouteImport.update({
    id: '/links/',
    path: '/links/',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameLinksLinkRoute =
  AuthenticatedShellProjectsNameLinksLinkRouteImport.update({
    id: '/links/$link',
    path: '/links/$link',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameMilestonesIndexRoute =
  AuthenticatedShellProjectsNameMilestonesIndexRouteImport.update({
    id: '/milestones/',
    path: '/milestones/',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameMilestonesMilestoneRoute =
  AuthenticatedShellProjectsNameMilestonesMilestoneRouteImport.update({
    id: '/milestones/$milestone',
    path: '/milestones/$milestone',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameModulesIndexRoute =
  AuthenticatedShellProjectsNameModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameModulesModuleRoute =
  AuthenticatedShellProjectsNameModulesModuleRouteImport.update({
    id: '/modules/$module',
    path: '/modules/$module',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameTasksTaskRoute =
  AuthenticatedShellProjectsNameTasksTaskRouteImport.update({
    id: '/tasks/$task',
    path: '/tasks/$task',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)
const AuthenticatedShellProjectsNameViewsViewRoute =
  AuthenticatedShellProjectsNameViewsViewRouteImport.update({
    id: '/views/$view',
    path: '/views/$view',
    getParentRoute: () => AuthenticatedShellProjectsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedShellIndexRoute
  '/inbox': typeof AuthenticatedShellInboxRoute
  '/my-tasks': typeof AuthenticatedShellMyTasksRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/projects/$name': typeof AuthenticatedShellProjectsNameRouteWithChildren
  '/projects/$name/settings': typeof AuthenticatedShellProjectsNameSettingsRoute
  '/projects/$name/': typeof AuthenticatedShellProjectsNameIndexRoute
  '/projects/$name/links/$link': typeof AuthenticatedShellProjectsNameLinksLinkRoute
  '/projects/$name/milestones/$milestone': typeof AuthenticatedShellProjectsNameMilestonesMilestoneRoute
  '/projects/$name/modules/$module': typeof AuthenticatedShellProjectsNameModulesModuleRoute
  '/projects/$name/tasks/$task': typeof AuthenticatedShellProjectsNameTasksTaskRoute
  '/projects/$name/views/$view': typeof AuthenticatedShellProjectsNameViewsViewRoute
  '/projects/$name/links/': typeof AuthenticatedShellProjectsNameLinksIndexRoute
  '/projects/$name/milestones/': typeof AuthenticatedShellProjectsNameMilestonesIndexRoute
  '/projects/$name/modules/': typeof AuthenticatedShellProjectsNameModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedShellIndexRoute
  '/inbox': typeof AuthenticatedShellInboxRoute
  '/my-tasks': typeof AuthenticatedShellMyTasksRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/projects/$name/settings': typeof AuthenticatedShellProjectsNameSettingsRoute
  '/projects/$name': typeof AuthenticatedShellProjectsNameIndexRoute
  '/projects/$name/links/$link': typeof AuthenticatedShellProjectsNameLinksLinkRoute
  '/projects/$name/milestones/$milestone': typeof AuthenticatedShellProjectsNameMilestonesMilestoneRoute
  '/projects/$name/modules/$module': typeof AuthenticatedShellProjectsNameModulesModuleRoute
  '/projects/$name/tasks/$task': typeof AuthenticatedShellProjectsNameTasksTaskRoute
  '/projects/$name/views/$view': typeof AuthenticatedShellProjectsNameViewsViewRoute
  '/projects/$name/links': typeof AuthenticatedShellProjectsNameLinksIndexRoute
  '/projects/$name/milestones': typeof AuthenticatedShellProjectsNameMilestonesIndexRoute
  '/projects/$name/modules': typeof AuthenticatedShellProjectsNameModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/_shell/inbox': typeof AuthenticatedShellInboxRoute
  '/_authenticated/_shell/my-tasks': typeof AuthenticatedShellMyTasksRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
  '/_authenticated/_shell/': typeof AuthenticatedShellIndexRoute
  '/_authenticated/_shell/projects/$name': typeof AuthenticatedShellProjectsNameRouteWithChildren
  '/_authenticated/_shell/projects/$name/settings': typeof AuthenticatedShellProjectsNameSettingsRoute
  '/_authenticated/_shell/projects/$name/': typeof AuthenticatedShellProjectsNameIndexRoute
  '/_authenticated/_shell/projects/$name/links/$link': typeof AuthenticatedShellProjectsNameLinksLinkRoute
  '/_authenticated/_shell/projects/$name/milestones/$milestone': typeof AuthenticatedShellProjectsNameMilestonesMilestoneRoute
  '/_authenticated/_shell/projects/$name/modules/$module': typeof AuthenticatedShellProjectsNameModulesModuleRoute
  '/_authenticated/_shell/projects/$name/tasks/$task': typeof AuthenticatedShellProjectsNameTasksTaskRoute
  '/_authenticated/_shell/projects/$name/views/$view': typeof AuthenticatedShellProjectsNameViewsViewRoute
  '/_authenticated/_shell/projects/$name/links/': typeof AuthenticatedShellProjectsNameLinksIndexRoute
  '/_authenticated/_shell/projects/$name/milestones/': typeof AuthenticatedShellProjectsNameMilestonesIndexRoute
  '/_authenticated/_shell/projects/$name/modules/': typeof AuthenticatedShellProjectsNameModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/my-tasks'
    | '/settings'
    | '/projects/$name'
    | '/projects/$name/settings'
    | '/projects/$name/'
    | '/projects/$name/links/$link'
    | '/projects/$name/milestones/$milestone'
    | '/projects/$name/modules/$module'
    | '/projects/$name/tasks/$task'
    | '/projects/$name/views/$view'
    | '/projects/$name/links/'
    | '/projects/$name/milestones/'
    | '/projects/$name/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/my-tasks'
    | '/settings'
    | '/projects/$name/settings'
    | '/projects/$name'
    | '/projects/$name/links/$link'
    | '/projects/$name/milestones/$milestone'
    | '/projects/$name/modules/$module'
    | '/projects/$name/tasks/$task'
    | '/projects/$name/views/$view'
    | '/projects/$name/links'
    | '/projects/$name/milestones'
    | '/projects/$name/modules'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_shell'
    | '/_authenticated/_shell/inbox'
    | '/_authenticated/_shell/my-tasks'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/'
    | '/_authenticated/_shell/projects/$name'
    | '/_authenticated/_shell/projects/$name/settings'
    | '/_authenticated/_shell/projects/$name/'
    | '/_authenticated/_shell/projects/$name/links/$link'
    | '/_authenticated/_shell/projects/$name/milestones/$milestone'
    | '/_authenticated/_shell/projects/$name/modules/$module'
    | '/_authenticated/_shell/projects/$name/tasks/$task'
    | '/_authenticated/_shell/projects/$name/views/$view'
    | '/_authenticated/_shell/projects/$name/links/'
    | '/_authenticated/_shell/projects/$name/milestones/'
    | '/_authenticated/_shell/projects/$name/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/': {
      id: '/_authenticated/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/inbox': {
      id: '/_authenticated/_shell/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedShellInboxRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/my-tasks': {
      id: '/_authenticated/_shell/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthenticatedShellMyTasksRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/projects/$name': {
      id: '/_authenticated/_shell/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/projects/$name/': {
      id: '/_authenticated/_shell/projects/$name/'
      path: '/'
      fullPath: '/projects/$name/'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameIndexRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/settings': {
      id: '/_authenticated/_shell/projects/$name/settings'
      path: '/settings'
      fullPath: '/projects/$name/settings'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameSettingsRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/links/': {
      id: '/_authenticated/_shell/projects/$name/links/'
      path: '/links'
      fullPath: '/projects/$name/links/'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameLinksIndexRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/links/$link': {
      id: '/_authenticated/_shell/projects/$name/links/$link'
      path: '/links/$link'
      fullPath: '/projects/$name/links/$link'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameLinksLinkRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/milestones/': {
      id: '/_authenticated/_shell/projects/$name/milestones/'
      path: '/milestones'
      fullPath: '/projects/$name/milestones/'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameMilestonesIndexRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/milestones/$milestone': {
      id: '/_authenticated/_shell/projects/$name/milestones/$milestone'
      path: '/milestones/$milestone'
      fullPath: '/projects/$name/milestones/$milestone'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameMilestonesMilestoneRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/modules/': {
      id: '/_authenticated/_shell/projects/$name/modules/'
      path: '/modules'
      fullPath: '/projects/$name/modules/'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameModulesIndexRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/modules/$module': {
      id: '/_authenticated/_shell/projects/$name/modules/$module'
      path: '/modules/$module'
      fullPath: '/projects/$name/modules/$module'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameModulesModuleRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/tasks/$task': {
      id: '/_authenticated/_shell/projects/$name/tasks/$task'
      path: '/tasks/$task'
      fullPath: '/projects/$name/tasks/$task'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameTasksTaskRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
    '/_authenticated/_shell/projects/$name/views/$view': {
      id: '/_authenticated/_shell/projects/$name/views/$view'
      path: '/views/$view'
      fullPath: '/projects/$name/views/$view'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameViewsViewRouteImport
      parentRoute: typeof AuthenticatedShellProjectsNameRoute
    }
  }
}

interface AuthenticatedShellProjectsNameRouteChildren {
  AuthenticatedShellProjectsNameSettingsRoute: typeof AuthenticatedShellProjectsNameSettingsRoute
  AuthenticatedShellProjectsNameIndexRoute: typeof AuthenticatedShellProjectsNameIndexRoute
  AuthenticatedShellProjectsNameLinksLinkRoute: typeof AuthenticatedShellProjectsNameLinksLinkRoute
  AuthenticatedShellProjectsNameMilestonesMilestoneRoute: typeof AuthenticatedShellProjectsNameMilestonesMilestoneRoute
  AuthenticatedShellProjectsNameModulesModuleRoute: typeof AuthenticatedShellProjectsNameModulesModuleRoute
  AuthenticatedShellProjectsNameTasksTaskRoute: typeof AuthenticatedShellProjectsNameTasksTaskRoute
  AuthenticatedShellProjectsNameViewsViewRoute: typeof AuthenticatedShellProjectsNameViewsViewRoute
  AuthenticatedShellProjectsNameLinksIndexRoute: typeof AuthenticatedShellProjectsNameLinksIndexRoute
  AuthenticatedShellProjectsNameMilestonesIndexRoute: typeof AuthenticatedShellProjectsNameMilestonesIndexRoute
  AuthenticatedShellProjectsNameModulesIndexRoute: typeof AuthenticatedShellProjectsNameModulesIndexRoute
}

const AuthenticatedShellProjectsNameRouteChildren: AuthenticatedShellProjectsNameRouteChildren =
  {
    AuthenticatedShellProjectsNameSettingsRoute:
      AuthenticatedShellProjectsNameSettingsRoute,
    AuthenticatedShellProjectsNameIndexRoute:
      AuthenticatedShellProjectsNameIndexRoute,
    AuthenticatedShellProjectsNameLinksLinkRoute:
      AuthenticatedShellProjectsNameLinksLinkRoute,
    AuthenticatedShellProjectsNameMilestonesMilestoneRoute:
      AuthenticatedShellProjectsNameMilestonesMilestoneRoute,
    AuthenticatedShellProjectsNameModulesModuleRoute:
      AuthenticatedShellProjectsNameModulesModuleRoute,
    AuthenticatedShellProjectsNameTasksTaskRoute:
      AuthenticatedShellProjectsNameTasksTaskRoute,
    AuthenticatedShellProjectsNameViewsViewRoute:
      AuthenticatedShellProjectsNameViewsViewRoute,
    AuthenticatedShellProjectsNameLinksIndexRoute:
      AuthenticatedShellProjectsNameLinksIndexRoute,
    AuthenticatedShellProjectsNameMilestonesIndexRoute:
      AuthenticatedShellProjectsNameMilestonesIndexRoute,
    AuthenticatedShellProjectsNameModulesIndexRoute:
      AuthenticatedShellProjectsNameModulesIndexRoute,
  }

const AuthenticatedShellProjectsNameRouteWithChildren =
  AuthenticatedShellProjectsNameRoute._addFileChildren(
    AuthenticatedShellProjectsNameRouteChildren,
  )

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellInboxRoute: typeof AuthenticatedShellInboxRoute
  AuthenticatedShellMyTasksRoute: typeof AuthenticatedShellMyTasksRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
  AuthenticatedShellIndexRoute: typeof AuthenticatedShellIndexRoute
  AuthenticatedShellProjectsNameRoute: typeof AuthenticatedShellProjectsNameRouteWithChildren
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellInboxRoute: AuthenticatedShellInboxRoute,
  AuthenticatedShellMyTasksRoute: AuthenticatedShellMyTasksRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
  AuthenticatedShellIndexRoute: AuthenticatedShellIndexRoute,
  AuthenticatedShellProjectsNameRoute:
    AuthenticatedShellProjectsNameRouteWithChildren,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
