/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellIndexRouteImport } from './routes/_authenticated/_shell/index'
import { Route as AuthenticatedShellInboxRouteImport } from './routes/_authenticated/_shell/inbox'
import { Route as AuthenticatedShellMyTasksRouteImport } from './routes/_authenticated/_shell/my-tasks'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell/settings'
import { Route as AuthenticatedShellProjectsNameRouteImport } from './routes/_authenticated/_shell/projects.$name'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellIndexRoute = AuthenticatedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellInboxRoute = AuthenticatedShellInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellMyTasksRoute =
  AuthenticatedShellMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProjectsNameRoute =
  AuthenticatedShellProjectsNameRouteImport.update({
    id: '/projects/$name',
    path: '/projects/$name',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedShellIndexRoute
  '/inbox': typeof AuthenticatedShellInboxRoute
  '/my-tasks': typeof AuthenticatedShellMyTasksRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/projects/$name': typeof AuthenticatedShellProjectsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedShellIndexRoute
  '/inbox': typeof AuthenticatedShellInboxRoute
  '/my-tasks': typeof AuthenticatedShellMyTasksRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/projects/$name': typeof AuthenticatedShellProjectsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/_shell/inbox': typeof AuthenticatedShellInboxRoute
  '/_authenticated/_shell/my-tasks': typeof AuthenticatedShellMyTasksRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
  '/_authenticated/_shell/': typeof AuthenticatedShellIndexRoute
  '/_authenticated/_shell/projects/$name': typeof AuthenticatedShellProjectsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inbox' | '/my-tasks' | '/settings' | '/projects/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inbox' | '/my-tasks' | '/settings' | '/projects/$name'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_shell'
    | '/_authenticated/_shell/inbox'
    | '/_authenticated/_shell/my-tasks'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/'
    | '/_authenticated/_shell/projects/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/': {
      id: '/_authenticated/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/inbox': {
      id: '/_authenticated/_shell/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedShellInboxRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/my-tasks': {
      id: '/_authenticated/_shell/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthenticatedShellMyTasksRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/projects/$name': {
      id: '/_authenticated/_shell/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof AuthenticatedShellProjectsNameRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellInboxRoute: typeof AuthenticatedShellInboxRoute
  AuthenticatedShellMyTasksRoute: typeof AuthenticatedShellMyTasksRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
  AuthenticatedShellIndexRoute: typeof AuthenticatedShellIndexRoute
  AuthenticatedShellProjectsNameRoute: typeof AuthenticatedShellProjectsNameRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellInboxRoute: AuthenticatedShellInboxRoute,
  AuthenticatedShellMyTasksRoute: AuthenticatedShellMyTasksRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
  AuthenticatedShellIndexRoute: AuthenticatedShellIndexRoute,
  AuthenticatedShellProjectsNameRoute: AuthenticatedShellProjectsNameRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
