/**
 * inspectLayerStructure.js  —  Phase 0 (read-only)
 *
 * PURPOSE: Build a complete, classified layer inventory for the rename skill.
 *          Collects, per shape: id, name, type, nameStatus, position/size hints,
 *          child signals, text props, fill/stroke flags, and component status —
 *          everything the inference phase (02-semantic-inference.md) needs.
 *
 * USAGE:   Paste into a single `execute_code` call. No mutations occur.
 *          Pass the returned `layers` to local inference reasoning.
 *
 * INPUTS:  RUN_ID_HERE   — short stable slug for this session (e.g. "rename-2026-06-05-a").
 *          SCOPE         — "page" (default), "selection" (a selected board), or "file".
 *
 * OUTPUT:  { runId, scope, pageName, totalShapes, estimatedPageWidth,
 *            estimatedPageHeight, stats, layers:[...] }
 *
 * NOTE: Verify any unfamiliar signature with penpot_api_info before relying on it
 *       (e.g. penpot_api_info('PenpotShape', 'isComponentInstance')).
 */

const RUN_ID = "RUN_ID_HERE";        // REPLACE-ME
const SCOPE = "page";                // REPLACE-ME if scoping to "selection" or "file"

// ── Resolve the traversal root from scope ──────────────────────────────────
const page = penpot.currentPage;
let root;
if (SCOPE === "selection" && penpot.selection && penpot.selection.length > 0) {
  root = penpot.selection[0];        // expected to be a board; verify with shapeStructure
} else {
  root = page.root;                  // current page (default)
}

// ── Collect every descendant shape (read-only) ─────────────────────────────
const allShapes = penpotUtils.findShapes(() => true, root) || [];

// ── Page-relative hints for structural inference ───────────────────────────
const topLevel = allShapes.filter(s => !s.parentId || s.parentId === root.id);
const estimatedPageWidth = Math.max(
  100, ...topLevel.map(s => (s.width || 0))
);
const estimatedPageHeight = Math.max(
  100, ...topLevel.map(s => ((s.y || 0) + (s.height || 0)))
);

// ── Name-status classification (the spine of the skill) ────────────────────
const isAutoGenerated = n =>
  /^(Board|Frame|Rectangle|Group|Ellipse|Text|Path|Bool|Image|Component|Vector)\s*\d*$/i.test(n || "");
const isSemantic = n =>
  /^(header|footer|nav|main|section|article|aside|form|dialog|figure|button|input|select|label|a|h[1-6]|p|small|caption|span|ul|ol|li|img|svg|icon|hr)([-_ ].*)?$/i.test(n || "");
const nameStatus = n => isSemantic(n) ? "semantic" : isAutoGenerated(n) ? "auto-generated" : "custom";

// ── Safe component-status read (instance vs. main shape) ───────────────────
function componentFlags(shape) {
  let instance = false, main = false;
  try {
    if (typeof shape.isComponentInstance === "function") instance = !!shape.isComponentInstance();
    // The main instance AND every shape inside it return isComponentMainInstance() === true.
    // Renaming any of these edits the component for ALL its copies -> out of the safe-set.
    if (typeof shape.isComponentMainInstance === "function") main = !!shape.isComponentMainInstance();
    else if (typeof shape.component === "function") main = !!shape.component() && !instance; // fallback (older API)
  } catch (e) { /* property/method absent on this shape type */ }
  return { isComponentInstance: instance, isMainComponent: main };
}

const layers = allShapes.map(shape => {
  const name = shape.name || "";
  const children = shape.children || [];
  const fills = shape.fills || [];
  const strokes = shape.strokes || [];
  const cf = componentFlags(shape);
  const firstFill = fills[0] || null;

  return {
    id: shape.id,
    name,
    type: shape.type,
    nameStatus: nameStatus(name),
    // position / size (read-only — never mutated here)
    x: Math.round(shape.x || 0),
    y: Math.round(shape.y || 0),
    width: Math.round(shape.width || 0),
    height: Math.round(shape.height || 0),
    isFullWidth: (shape.width || 0) >= estimatedPageWidth * 0.8,
    isAtTop: (shape.y || 0) < 120,
    isAtBottom: (shape.y || 0) > estimatedPageHeight * 0.8,
    // hierarchy
    parentId: shape.parentId || null,
    childCount: children.length,
    childTypes: [...new Set(children.map(c => c.type))].join(","),
    // fills / strokes (flags only — arrays are immutable item-by-item)
    hasSolidFill: fills.some(f => f.fillColor && (f.fillOpacity == null || f.fillOpacity > 0)),
    hasImageFill: fills.some(f => !!f.fillImage),
    fillColor: firstFill && firstFill.fillColor ? firstFill.fillColor : null,
    hasStrokeOnly: strokes.length > 0 &&
      (fills.length === 0 || fills.every(f => f.fillOpacity === 0)),
    borderRadius: shape.borderRadius || 0,
    // typography
    isText: shape.type === "text",
    fontSize: shape.fontSize || null,
    fontWeight: shape.fontWeight || null,
    fontFamily: shape.fontFamily || null,
    characters: shape.characters ? String(shape.characters).substring(0, 60) : null,
    // component status (decides skip in Phase 2)
    isComponentInstance: cf.isComponentInstance,
    isMainComponent: cf.isMainComponent,
    // layout
    hasLayout: !!shape.layout,
    layoutDir: shape.layout && shape.layout.dir ? shape.layout.dir : null,
  };
});

const stats = {
  autoGenerated: layers.filter(l => l.nameStatus === "auto-generated").length,
  alreadySemantic: layers.filter(l => l.nameStatus === "semantic").length,
  custom: layers.filter(l => l.nameStatus === "custom").length,
  componentInstances: layers.filter(l => l.isComponentInstance).length,
  mainComponents: layers.filter(l => l.isMainComponent).length,
  textNodes: layers.filter(l => l.isText).length,
};

return {
  runId: RUN_ID,
  scope: SCOPE,
  pageName: page.name,
  totalShapes: allShapes.length,
  estimatedPageWidth,
  estimatedPageHeight,
  stats,
  layers,
};
